### ISSUE TITLE
remove `delete` action (backspace) on statements loaded

### ISSUE THREAD

**Issue by jaromil** [dyne/zencode-tools#7]
After deleting a search the backspace hit deletes loaded statements, this should not happen.

Also handy to have `esc` and `ctrl-g` as keys to quit the `/` search.

Worth thinking if zenexplorer should start directly in "search mode" since we use it just for that, then `/` key is not needed.

**Comment by albertolerda** [comment]
The main issue about deleting statements is fixed.

`esc` key is enabled to exit the search.

What if the user wants to just "navigate" the statements? `/` is quite standard to start the search.

**Comment by jaromil** [comment]
@albertolerda maybe without delete statements is better and does not need restarting, but I expect to navigate with arrows or pg-updown, while all alphabetic keys activate search...

**Comment by albertolerda** [comment]
I see, the problem is that we don't have control easily over the search feature, it is implemented inside the list component of bubbletea.

**Comment by jaromil** [comment]
right, I forgot that, looked at it once. It's ok then thanks for fixing the delete was very annoying!!
